### ISSUE TITLE
Use tropopause module directly

### ISSUE THREAD

**Issue by zxdawn** [CohenBerkeleyLab/WRF_Utils#3]
WRF-Chem has the [module](https://github.com/CohenBerkeleyLab/WRF-Chem-R2SMH/blob/master/chem/module_tropopause.F) of calculating tropopause based on [Reichler, T., M. Dameris, and R. Sausen (2003)](https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1029/2003GL018240). Why not use it directly?

**Comment by joshua-laughner** [comment]
This would require rerunning WRF simulations that took 2 years to complete. But it is good to know that it is an option.

**Comment by zxdawn** [comment]
@joshua-laughner Maybe you can just use the algorithm to calculate the tropopause instead of running again.

**Comment by zxdawn** [comment]
In my opinion, instead of using 100 hPa as the top of model, it's better to set 10 hPa and 41 vertical pressure levels. Otherwise, some cell's tropopause is higher than the top of model, especially the west of U.S..

**Comment by joshua-laughner** [comment]
The problem is we use NARR meteorology for initial and boundary conditions and it only goes up to 100 hPa, so NARR and a 10 hPa top are incompatible as far as I know:

https://www.esrl.noaa.gov/psd/data/gridded/data.narr.html

Please also understand: the model configuration we used for the BEHR profiles had to be decided >2 years ago when we started the CONUS simulations. We made the best choices we could at the time, and until and unless we decide to rerun those simulations, there is a limit to how much we can change about the model runs.

At present, further work on calculating the tropopause pressure from WRF is not our focus for BEHR. We are instead evaluating other options that will be simpler to implement and maintain.

**Comment by zxdawn** [comment]
Oh! I neglected the top of Reanalysis data ... Thank you for your remind!
